---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pheme
  namespace: instana-agent
  labels:
    app: pheme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pheme 
  template:
    metadata:
      labels:
        app: pheme 
    spec:
      containers:
      - name: pheme
        image: nfinstana/pheme
        imagePullPolicy: Always
        ports:
        - name: status
          containerPort: 8008
        livenessProbe:
          httpGet:
            path: /healthz
            port: status
      - name: sidecar
        image: nfinstana/pheme
        imagePullPolicy: Always
        command: ["/app", "-listen=:8081"]
        ports:
        - name: sidecar
          containerPort: 8081
        livenessProbe:
          httpGet:
            path: /healthz
            port: sidecar
      serviceAccount: instana-agent
      serviceAccountName: instana-agent
      dnsPolicy: ClusterFirst